'use client';
import {useEffect,useState} from 'react';
import {Search,ExternalLink,RefreshCw} from 'lucide-react';
import {money,percent,type Stock} from '@/lib/market';
import {kindNames,periodNames,type NaverKind,type NaverPeriod,type NaverRanking,type NaverMembers} from '@/lib/naver';
const base=process.env.NEXT_PUBLIC_BASE_PATH||'';
const cls=(n:number)=>n>0?'up':n<0?'down':'neutral';
const stamp=(s:string)=>new Date(s).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});
export function NaverExplorer({refreshKey,onStock}:{refreshKey:number;onStock:(stock:Stock)=>void}){
 const [kind,setKind]=useState<NaverKind>('industry'),[period,setPeriod]=useState<NaverPeriod>('daily'),[ranking,setRanking]=useState<NaverRanking|null>(null),[selected,setSelected]=useState(''),[members,setMembers]=useState<NaverMembers|null>(null),[tick,setTick]=useState(0),[query,setQuery]=useState(''),[market,setMarket]=useState('ALL'),[sort,setSort]=useState('value'),[rankBusy,setRankBusy]=useState(true),[memberBusy,setMemberBusy]=useState(false),[rankError,setRankError]=useState(''),[memberError,setMemberError]=useState('');
 useEffect(()=>{const t=setInterval(()=>setTick(x=>x+1),60000);return()=>clearInterval(t);},[]);
 useEffect(()=>{
  const controller=new AbortController();setRankBusy(true);setRankError('');
  fetch(`${base}/api/naver?kind=${kind}&period=${period}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const j=await r.json() as NaverRanking&{error?:string};if(!r.ok)throw Error(j.error);if(controller.signal.aborted)return;setRanking(j);setSelected(prev=>j.items.some((x:{id:string})=>x.id===prev)?prev:j.items[0]?.id||'');}).catch(e=>{if(!controller.signal.aborted)setRankError(e.message);}).finally(()=>{if(!controller.signal.aborted)setRankBusy(false);});
  return()=>controller.abort();
 },[kind,period,tick,refreshKey]);
 useEffect(()=>{
  if(!selected)return;const controller=new AbortController();setMemberBusy(true);setMemberError('');
  fetch(`${base}/api/naver?kind=${kind}&id=${selected}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const j=await r.json() as NaverMembers&{error?:string};if(!r.ok)throw Error(j.error);if(!controller.signal.aborted)setMembers(j);}).catch(e=>{if(!controller.signal.aborted)setMemberError(e.message);}).finally(()=>{if(!controller.signal.aborted)setMemberBusy(false);});return()=>controller.abort();
 },[kind,selected,tick,refreshKey]);
 function changeKind(k:NaverKind){if(k===kind)return;setKind(k);setRanking(null);setSelected('');setMembers(null);setQuery('');}
 function changePeriod(p:NaverPeriod){if(p===period)return;setPeriod(p);setRanking(null);}
 const sector=ranking?.items.find(x=>x.id===selected);
 const stocks=(members?.stocks||[]).filter(s=>market==='ALL'||s.market===market).slice().sort((a,b)=>sort==='change'?b.change-a.change:sort==='fall'?a.change-b.change:sort==='volume'?b.volume-a.volume:sort==='marketCap'?b.marketCap-a.marketCap:b.value-a.value);
 const source=`https://stock.naver.com/market/stock/kr/${kind==='groups'?'groups':kind}/${sector?.rank||1}${sector?'?no='+sector.id:''}`;
 return <section className="naver-explorer" aria-label="네이버 업종·테마 순위">
  <div className="naver-heading"><div className="naver-tabs" aria-label="네이버 분류">{(Object.keys(kindNames) as NaverKind[]).map(k=><button key={k} aria-pressed={kind===k} className={kind===k?'selected':''} onClick={()=>changeKind(k)}>{kindNames[k]}</button>)}</div><a href={source} target="_blank" rel="noreferrer">네이버 원본 <ExternalLink size={13}/></a></div>
  <div className="naver-update"><span><i/>1분 자동 업데이트</span><small>{ranking?'수집 '+stamp(ranking.fetchedAt)+' KST':'네이버 자료 수집 중'}</small><button onClick={()=>setTick(x=>x+1)} aria-label="네이버 순위 새로고침"><RefreshCw size={14} className={rankBusy||memberBusy?'spin':''}/></button></div>
  {rankError&&<div className="notice" role="alert">{rankError}{ranking&&' 마지막 수집 자료를 표시합니다.'}<button onClick={()=>setTick(x=>x+1)}>다시 시도</button></div>}
  <div className="naver-content"><aside className="naver-sector-list"><div className="segmented naver-period" aria-label="순위 기간">{(Object.keys(periodNames) as NaverPeriod[]).map(p=><button key={p} className={period===p?'selected':''} aria-pressed={period===p} onClick={()=>changePeriod(p)}>{periodNames[p]}</button>)}</div><label className="search naver-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={kindNames[kind]+' 검색'} aria-label="네이버 분류 검색"/></label><div className="naver-sector-scroll" tabIndex={0} role="region" aria-label={periodNames[period]+' '+kindNames[kind]+' 순위'} aria-busy={rankBusy}>{ranking?.items.filter(s=>s.name.includes(query)).map(s=><button key={s.id} className={'naver-sector '+(s.id===selected?'selected':'')} aria-pressed={s.id===selected} onClick={()=>{if(selected!==s.id){setSelected(s.id);setMembers(null);}}}><span className="naver-sector-rank">{s.rank}</span><span className="naver-sector-name"><b>{s.name}</b><small>상승 <em className="up">{s.rise}</em> 보합 {s.flat} 하락 <em className="down">{s.fall}</em></small></span><strong className={cls(s.change)}>{percent(s.change)}</strong></button>)}{!ranking&&<div className="empty">{rankBusy?'네이버 순위 불러오는 중…':'순위를 불러오지 못했습니다.'}</div>}{ranking&&!ranking.items.some(s=>s.name.includes(query))&&<div className="empty">검색된 분류가 없습니다.</div>}</div><p className="naver-caption">{periodNames[period]} 평균 등락률 순위 · 네이버 제공<br/>총 {ranking?.items.length??0}개 {kindNames[kind]}</p></aside>
  <div className="naver-detail" aria-busy={memberBusy}>
   {sector?<><div className="naver-detail-title"><h2>{sector.name} <span className={cls(sector.change)}>{percent(sector.change)}</span></h2><small>{sector.updatedAt.slice(0,10)} 기준 · {periodNames[period]}</small></div>
   <div className="naver-summary"><div><span>{sector.volume===null?'시가총액':'거래량'}</span><b>{sector.volume===null?money(sector.marketCap):sector.volume.toLocaleString()+'주'}</b><span>{sector.value===null?'기간 평균 등락률':'거래대금'}</span><b className={sector.value===null?cls(sector.change):''}>{sector.value===null?percent(sector.change):money(sector.value)}</b></div><div><span>{periodNames[period]} 상승률 TOP 기업</span>{sector.topChange.map((s,i)=><a className="naver-top-company" key={s.code} href={'https://stock.naver.com/domestic/stock/'+s.code+'/price'} target="_blank" rel="noreferrer"><small>{i+1}</small><b>{s.name}</b><strong className={cls(s.value)}>{percent(s.value)}</strong></a>)}</div><div><span>시가총액 TOP 기업</span>{sector.topCap.map((s,i)=><a className="naver-top-company" key={s.code} href={'https://stock.naver.com/domestic/stock/'+s.code+'/price'} target="_blank" rel="noreferrer"><small>{i+1}</small><b>{s.name}</b><strong>{money(s.value)}</strong></a>)}</div></div>
   <div className="naver-company-heading"><h3>구성 기업 순위 <span>{stocks.length}</span></h3><small>최신 시세 · 일간 등락률</small></div><div className="naver-company-controls"><div className="segmented">{[['ALL','전체'],['KOSPI','코스피'],['KOSDAQ','코스닥']].map(([value,label])=><button key={value} className={market===value?'selected':''} onClick={()=>setMarket(value)}>{label}</button>)}</div><select aria-label="구성 기업 정렬" value={sort} onChange={e=>setSort(e.target.value)}>{[['value','거래대금 상위'],['marketCap','시가총액 상위'],['change','상승률 상위'],['fall','하락률 상위'],['volume','거래량 상위']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
   {memberError&&<div className="notice" role="alert">{memberError}{members&&' 마지막 수집 자료를 표시합니다.'}<button onClick={()=>setTick(x=>x+1)}>다시 시도</button></div>}
   <div className="naver-table-wrap" tabIndex={0} role="region" aria-label="네이버 구성 기업 순위표"><table className="naver-company-table"><thead><tr><th>순위 / 기업명</th><th>현재가</th><th>일간 등락률</th><th>거래대금</th><th>거래량</th><th>시가총액</th></tr></thead><tbody>{stocks.map((s,i)=><tr key={s.code}><td><button onClick={()=>onStock(s)}><span>{i+1}</span><b>{s.name}<small>{s.code} · {s.market}</small></b></button></td><td className={cls(s.change)}>{s.price.toLocaleString()}</td><td className={cls(s.change)}>{percent(s.change)}</td><td>{money(s.value)}</td><td>{s.volume.toLocaleString()}</td><td>{money(s.marketCap)}</td></tr>)}</tbody></table>{!stocks.length&&<div className="empty">{memberBusy?'구성 기업 불러오는 중…':memberError?'구성 기업 수집 실패':'이 시장의 구성 기업이 없습니다.'}</div>}</div><p className="naver-caption">업종·테마·그룹사 순위와 상승률 TOP은 선택한 기간의 네이버 원본입니다.<br/>구성 기업의 현재가·등락률·거래대금·거래량은 네이버 최신 일간 시세입니다.{members&&' 수집 '+stamp(members.fetchedAt)+' KST'}</p>
   </>:<div className="empty">{rankBusy?'순위를 불러오고 있습니다.':'왼쪽에서 '+kindNames[kind]+'을 선택해 주세요.'}</div>}
  </div></div>
 </section>;
}
