export type Stock={code:string;name:string;price:number;change:number;value:number;market:string;sector?:string;upper?:boolean};
export type Sector={id:string;name:string;change:number;value:number;count:number;rise:number;date:string;kind:'theme'|'industry';stocks:Stock[];score:number};
export type MarketData={fetchedAt:string;date:string;stocks:Stock[];themes:Sector[];industries:Sector[];judal:{id:string;name:string;change:number}[];indices:{name:string;price:string;change:number}[];warnings:string[];live:boolean;historySaved?:boolean};
export const sourceLinks=[['네이버 테마','https://stock.naver.com/market/stock/kr/theme/1'],['네이버 업종','https://stock.naver.com/market/stock/kr/industry/1'],['네이버 거래대금','https://stock.naver.com/market/stock/kr/stocklist/priceTop'],['주달 테마','https://www.judal.co.kr/?view=themeList']];
const num=(x:unknown)=>Number(String(x??0).replace(/,/g,''))||0;
export function normalizeStock(s:Record<string,unknown>):Stock{return {code:String(s.itemCode??s.itemcode),name:String(s.stockName??s.itemname),price:num(s.closePrice??s.nowPrice),change:num(s.fluctuationsRatio??s.prevChangeRate),value:s.tradeAmount!=null?num(s.tradeAmount):num(s.accumulatedTradingValue)*1e6,market:String(s.sosok)==='0'?'KOSPI':'KOSDAQ',upper:String(s.upDownGb)==='1'||(s.compareToPreviousPrice as {name?:string})?.name==='UPPER_LIMIT'};}
export function normalizeSectors(rows:Record<string,unknown>[],kind:'theme'|'industry'):Sector[]{const max=Math.max(1,...rows.map(s=>num(s.totalAccAmount)));return rows.map(s=>({id:String(s.no),name:String(s.name),change:num(s.changeRate),value:num(s.totalAccAmount)*1000,count:num(s.totalCnt),rise:num(s.riseCnt),date:String(s.thistime).slice(0,8).replace(/(\d{4})(\d{2})(\d{2})/,'$1-$2-$3'),kind,stocks:[],score:Math.round(50*num(s.totalAccAmount)/max+30*Math.min(Math.max(num(s.changeRate),0)/10,1)+20*num(s.riseCnt)/Math.max(1,num(s.totalCnt)))})).sort((a,b)=>b.score-a.score);}
export function money(n:number){return n>=1e12?`${(n/1e12).toFixed(2)}조`:`${(n/1e8).toLocaleString('ko-KR',{maximumFractionDigits:0})}억`;}
export function percent(n:number){return `${n>0?'+':''}${n.toFixed(2)}%`;}
